### ISSUE TITLE
VSCode v1.66 support

### ISSUE THREAD

**Issue by vanowm** [TatsuyaNakamori/vscode-RegexHighlighter#1]
No longer works in VSCode v1.66.1 on Windows 10 21H2 x64
getting error:

```
[2022-04-09 23:26:39.843] [renderer1] [error] Cannot read properties of undefined (reading 'nestDepth'): TypeError: Cannot read properties of undefined (reading 'nestDepth')
    at Object.updateDecorations (e:\Program Files\VSCode\data\extensions\tatsuyanakamori.regexhighlighter-0.0.1\out\regexHighlighter.js:140:25)
    at e:\Program Files\VSCode\data\extensions\tatsuyanakamori.regexhighlighter-0.0.1\out\extension.js:29:30
    at u.invoke (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:86:66000
    at u.invoke (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at E.acceptDocumentsAndEditorsDelta (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:75931)
    at E.$acceptDocumentsAndEditorsDelta (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:74020)
    at i._doInvokeHandler (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)
    at i._invokeHandler (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)
    at i._receiveRequest (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171)
    at i._receiveOneMessage (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)
    at e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947
    at u.invoke (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275
    at u.invoke (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at o._receiveMessage (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)
    at e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149
    at u.invoke (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at v.acceptChunk (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)
    at e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995
    at Socket.P (e:\Program Files\VSCode\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by TatsuyaNakamori** [comment]
Thanks for the bug report.
We will look into it, please wait.

**Comment by TatsuyaNakamori** [comment]
Sorry for the late reply.

I was working on fixing a bug and the same feature was added in the official VSCode.
https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default

Although some usability is different, it works more stable than my script.

In other words... I would like to close the development of this extension and leave the future of this feature to the VSCode official.

Thank you for using my tool.
